blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/EveronLife/EveronLife/discussions/categories/ideas
    about: Suggest new gameplay or technical features
